
services:
  postgres:
    image: postgres:15
    container_name: aura-postgres
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: api_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aura-network
volumes:
  postgres_data:

networks:
  aura-network:
    driver: bridge
